### ISSUE TITLE
Errors trying to connect to target

### ISSUE THREAD

**Issue by KyferEz** [Balasys/dheater#5]
@c0r0n3r I can provide wireshark if needed in order to understand why the script fails despite having communication.

Output:
C:\Users\t>dheat --protocol tls gw.t.local
Network error oocuerd while checking whether Diffie-Hellman ephemeral (DHE) key exchange is supported by the server; uri="gw.t.local", error="connection to target cannot be established"

C:\Users\t>dheat --protocol tls gw.t.local
Network error oocuerd while checking whether Diffie-Hellman ephemeral (DHE) key exchange is supported by the server; uri="gw.t.local", error="no response received from target"

**Comment by c0r0n3r** [comment]
A `pcap` file would be so useful. Without there can be just guesses.

**Comment by KyferEz** [comment]
Here are 3 tests with different sets of Ciphers bound to the server. pcap is at link; there's a separate file for each test and named as such: https://drive.google.com/drive/folders/1tluvSlcSBumyKCswnjYF5qeUnOgitcQz?usp=sharing

1st test error
Error:
'''C:\Users\T>dheat --protocol tls gw.t.local
Network error oocuerd while checking whether Diffie-Hellman ephemeral (DHE) key exchange is supported by the server; uri="gw.t.local", error="no response received from target"'''


2nd test error:
Error:
'''C:\Users\T>dheat --protocol tls gw.t.local
Traceback (most recent call last):
  File "c:\programs\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programs\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Programs\Python38-32\Scripts\dheat.exe\__main__.py", line 7, in <module>
  File "c:\programs\python38-32\lib\site-packages\dheater\__main__.py", line 346, in main
    enforcer = DHEnforcerThreadTLS(args.uri, args.timeout, pre_check_result)
  File "<attrs generated init dheater.__main__.DHEnforcerThreadBase>", line 15, in __init__
  File "c:\programs\python38-32\lib\site-packages\dheater\__main__.py", line 102, in __attrs_post_init__
    self._pre_check()
  File "c:\programs\python38-32\lib\site-packages\dheater\__main__.py", line 264, in _pre_check
    protocol_version = min(analyzer_result_versions.versions)
ValueError: min() arg is an empty sequence'''

3rd test error:
Error:
'''C:\Users\T>dheat --protocol tls gw.t.local
Network error oocuerd while checking whether Diffie-Hellman ephemeral (DHE) key exchange is supported by the server; uri="gw.t.local", error="no response received from target"'''

**Comment by c0r0n3r** [comment]
It seems that the reason of the error in 2nd test case is the fact that the server does not support DHE. Could you test it again with the latest version of dheater (0.2.4)?

**Comment by c0r0n3r** [comment]
@KyferEz please reopen if the issue still exists in the latest version.
