### ISSUE TITLE
gnuTLS support?

### ISSUE THREAD

**Issue by Lockhead** [Balasys/dheater#6]
It seems like it does not work against gnuTLS implementations, but the general problem described in the CVE sounds like it should. Any chance to get it modified for gnuTLS as well...

**Comment by c0r0n3r** [comment]
Yes, it should work against GnuTLS. I've modified the TLS implementation to wait for the server key exchange message, which proofs that the server has calculated the DH public key. It seems that it solves the issue with GnuTLS and makes the working more predictable. Could you give me a feedback about the fix?

**Comment by Lockhead** [comment]
Seems to work, we now see similar behavior from gnutls-serv as we saw from OpenSSL

**Comment by c0r0n3r** [comment]
@Lockhead, thanks for the feedback. I will merge soon.
