### ISSUE TITLE
Anti-DDoS Mechanism in openssh-8.5p1

### ISSUE THREAD

**Issue by kircherlike** [Balasys/dheater#8]
Once, I also submitted a ddos question to the openssh community: https://bugzilla.mindrot.org/show_bug.cgi?id=3211

They added the configuration items PerSourceMaxStartups and PerSourceNetBlockSize to openssh-8.5p1. I think that the two parameters can be properly configured to prevent "dheat" from attacking OpenSSH.

**Comment by c0r0n3r** [comment]
Thank for the info. If I understand it well these configuration items should be added to the documentation of D(HE)ater, but I have no other thing to do.
