### ISSUE TITLE
not able to use

### ISSUE THREAD

**Issue by sourav592** [Balasys/dheater#9]
Hello,

I'm very new to this cybersecurity field Please anyone help me out with this problem.
_### Note I have replace website name with ConfidentialWebsite.com_

**When I use tls protocol I'm getting this error :-**

dheat --protocol tls ConfidentialWebsite.com
 Traceback (most recent call last):
   File "/usr/local/bin/dheat", line 8, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.9/dist-packages/dheater/__main__.py", line 512, in main
     enforcer = DHEnforcerThreadTLS(args.uri, args.timeout, pre_check_result)
   File "<attrs generated init dheater.__main__.DHEnforcerThreadBase>", line 14, in __init__
   File "/usr/local/lib/python3.9/dist-packages/dheater/__main__.py", line 125, in __attrs_post_init__
     self._pre_check()
   File "/usr/local/lib/python3.9/dist-packages/dheater/__main__.py", line 390, in _pre_check
     if is_tls_1_3:
 NameError: name 'is_tls_1_3' is not defined

**When I use ssh protocol I'm getting this error :-**

dheat --protocol ssh  ConfidentialWebsite.com                                                                                                     
 Network error oocuerd while checking whether Diffie-Hellman ephemeral (DHE) key exchange is supported by the server; 
 uri="ConfidentialWebsite.com", error="connection to target cannot be established"

![AddText_02-02-08 37 54](https://user-images.githubusercontent.com/75566211/152180887-f145a742-cc8b-4952-9f68-eba70c8bf663.jpg)

**Comment by c0r0n3r** [comment]
As you are a newbie, please let me warn you that starting your journey in cybersecurity with a possibly destructive act not the best idea. Be so careful when you use that tool. Consider the legal and other consequences. Double-check the circumstances.

**Comment by sourav592** [comment]
But, I have permission for doing this because it's my friends website and **https://hostedscan.com/**  had found this vulnerability, with the help of this tool I just want to know that is the website is vulnerable or not, so that I can tell him about this. If you have some time then please tell me about this, it is very serious issue.

**Comment by c0r0n3r** [comment]
If this is the case, then everything is fine. It was just a friendly reminder.

**Comment by sourav592** [comment]
bro, can you please tell me that why the error is coming in this tool while performing the attack. Or am I using the tool incorrectly?  The website is having HIGH SEVERITY that is why I'm asking you.

**Comment by c0r0n3r** [comment]
I have already fixed the issue, closed the bug, and released a new version (0.3.1).

Feel free to contact me. You can find a link to my web page and Twitter account on my profile page.
